# object classifier boot.py
# generated by maixhub.com

import sensor, image, lcd, time
import KPU as kpu
from Maix import GPIO
from fpioa_manager import fm
from board import board_info
from machine import Timer,PWM
import gc, sys

tim1 = Timer(Timer.TIMER0, Timer.CHANNEL0, mode=Timer.MODE_PWM)
tim2 = Timer(Timer.TIMER0, Timer.CHANNEL1, mode=Timer.MODE_PWM)
tim3 = Timer(Timer.TIMER0, Timer.CHANNEL2, mode=Timer.MODE_PWM)
tim4 = Timer(Timer.TIMER0, Timer.CHANNEL3, mode=Timer.MODE_PWM)

ch1 = PWM(tim1, freq=256, duty=50, pin=24)
ch2 = PWM(tim2, freq=256, duty=50, pin=32)
ch3 = PWM(tim3, freq=256, duty=50, pin=13)
ch4 = PWM(tim4, freq=256, duty=50, pin=12)

duty = 0
ch1.duty(duty)
ch2.duty(duty)
ch3.duty(duty)
ch4.duty(duty)

def straight():
    ch1.duty(90)
    ch2.duty(0)
    ch3.duty(0)
    ch4.duty(90)

def right_move():
    ch1.duty(90)
    ch2.duty(0)
    ch3.duty(0)
    ch4.duty(0)

def left_move():
    ch1.duty(0)
    ch2.duty(0)
    ch3.duty(0)
    ch4.duty(90)

def stop():
    ch1.duty(0)
    ch2.duty(0)
    ch3.duty(0)
    ch4.duty(0)


fm.register(21, fm.fpioa.GPIOHS0)
btn = GPIO(GPIO.GPIOHS0, GPIO.IN ,GPIO.PULL_UP)


sensor_window=(224, 224)
lcd_rotation=0
sensor_hmirror=False
sensor_vflip=True

sensor.reset()
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.set_windowing(sensor_window)
sensor.set_hmirror(sensor_hmirror)
sensor.set_vflip(sensor_vflip)
sensor.run(1)

lcd.init(type=1)
lcd.rotation(lcd_rotation)
lcd.clear(lcd.WHITE)

state_previous = 1
count = 0

try:
    img = sensor.snapshot()
    lcd.display(img)
except Exception:
    img = image.Image(size=(320, 240))
    img.draw_string(90, 110, "loading model...", color=(255, 255, 255), scale=2)
    lcd.display(img)

task = kpu.load(0x300000)

labels = ["no", "paper", "rock", "scissor"]

try:
    while(True):
        img = sensor.snapshot()
        state_current = btn.value()
        if state_current == 0:
            if state_previous == 1:
                count = count + 1
                state_previous = 0
                ch1.duty(0)
                ch2.duty(0)
                ch3.duty(0)
                ch4.duty(0)
                img.clear()
                img.draw_string(80,100,"END", color=(255, 0, 0),scale=4)
                lcd.display(img)
                break
        t = time.ticks_ms()
        fmap = kpu.forward(task, img)
        t = time.ticks_ms() - t
        plist=fmap[:]
        pmax=max(plist)
        pmin=min(plist)
        max_index=plist.index(pmax)
        img.draw_string(0,0, "%.2f : %s " %(pmax, labels[max_index].strip()), scale=2)
        if max_index == 0 :
            stop()
        elif max_index == 1 :
            straight()
        elif max_index == 2 :
            left_move()
        elif max_index == 3 :
            right_move()
        time.sleep_ms(10)
        img.draw_string(0,25, "min: %.2f" %(pmin), scale=2)
        img.draw_string(0, 200, "t:%dms" %(t), scale=2)
        lcd.display(img)
except Exception as e:
    sys.print_exception(e)